<?xml version="1.0" encoding="utf-8" ?>


<Stack xmlns="http://tempuri.org/CardData.xsd">
  <Settings>
    <TopCard>
      <Language>English</Language>
    </TopCard>
    <BottomCard>
      <Language>English</Language>
    </BottomCard>
  </Settings>
  <Cards>
    <Card Stack="unlearned">
      <Front>C</Front>
      <Back>Carbon</Back>
    </Card>
    <Card Stack="unlearned">
      <Front>O</Front>
      <Back>Oxygen</Back>
    </Card>
    <Card Stack="unlearned">
      <Front>Au</Front>
      <Back>Gold</Back>
    </Card>
    <Card Stack="unlearned">
      <Front>U</Front>
      <Back>Uranium</Back>
    </Card>
    <Card Stack="unlearned">
      <Front>W</Front>
      <Back>Tungsten</Back>
    </Card>
  </Cards>
</Stack>